sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sundarblr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sundarblr/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerReact-env-1"
   bucket_name: "elasticbeanstalk-us-east-1-222869217357"
   bucket_path: "docker-react"
   on:
    branch: main
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
      secure: "$AWS_SECRET_KEY"
