sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sundarblr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sundarblr/docker-react npm run test



