# Specify a base image
#FROM node:alpine
FROM node:12.18.1

WORKDIR /app

# Install some depenendencies
COPY package.json ./

RUN npm install
COPY . .

EXPOSE 3000

# Default command
CMD ["npm", "run", "start"]
